/**
 * 渠道首页需要用到的lui stateKey
 * 增加展位必须在这里增加对应的key
 * */
export default [
  'pullDownNavigate',
  'pullUpNavigate',
  'homeNavigateBar',
  'homeNavigateBarSearch',
  'backgroundImage',
  'bigPromotionImage',
  'sologan',
  'shortcutMenu',
  'bannerWithoutBorder',
  'bannerWithoutBorder$2',
  'largeLoan',
  'saveMoneyCard',
  'cmbWelfare',
  'financialServices',
  'listAdv',
  'listAdv$2',
  'newCustomerCoupons',
  'row2Column2Swiper',
  // 'imageTextEntry',
  // 'horizontalFourMoreScroll',
  'rownColumn3Card',
  'twoColumnAdv$1',
  'twoColumnAdv$2',
  'twoColumnAdv$3',
  'row2Column2TextImg',
  'contentInformation$1',
  'contentInformation$2',
  'contentInformation$3',
  'aboutUs',
  'brandText',
  'floatTopNotice',
  'bottomLogin',
  'floatImage',
  'dialog',
  'urgingPaymentDialog',
  'ifHasLoan',
  'virtualChannelOverdueSlogan',
  'virtualChannelRepayServices',
  'channelFinancialServices',
  'channelShortcutMenu',
  // 'publicDetainDialog',
  'channelLoanSpecialist',
  'virtualIdCommon',
  'topTextPropaganda',
  'virtualAlipayBigPromotionImg',
  'rowsImgs2Title',
  'rownColumn3Card$1',
  'rownColumn3Card$2',
  'marqueeTips',
  'rownColumn2Card$1',
  'rownColumn2Card$2',
  'wechatGuideCollect',
  'videoPlayColumn2',
  'rowsColumnOneTextbox',
  'channelNewFinancialServices',
  'imageTextSwiper'
];
